#+TITLE: Case Notes and Questions
#+AUTHOR: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup

* Concepts to Review/Highlight:
** Goal of the firm
The relationship between the goal of the firm and US state laws of incorporation.  Brief note of laws in other countries.
** Ownership of the firm
-  Who owns the firm's and how do they exercise control over the firm?
-  Two aspects of ownership, (1) control and (2) residual claim on cash flows.
-  Did Ben and Jerry's charter attempt to separate the two aspects of ownership? 
** Agency Problem and its resolutions through the Takeover (market for corporate control)
** Du Pont Identity
The ROE is mentioned throughout the case as a performance metric.  Show the drivers of ROE through the Du Pont identity.  

$$ROE = (Profit\ Margin)(Total\ Asset\ Turnover)(Equity\ Multiplier)$$

* Discussion Questions 
1. What was Jerry's IPO method and what effect did it have on:
    - The amount of capital raised.
    - The control of the firm.
2. What do you think of the interview on page 42? Would this make you more or less confident to invest in Ben and Jerry's?  Possibly consider this question in relation to the following anecdote on page 42.
3. How do we want management to increase ROE, and alternatively what method is irrelevant?
4. What do you think is the correlation, if any, between "caring capitalism" and the stock price?  Consider the mission statement on page 43.  
5.  Why did Ben and Jerry's have differential voting rights? 
6.  What was the effect of the corporate charter restrictions (page 44).  Do they make changes easier or more difficult? Do they increase or decrease the founders' (Ben and Jerry) control.
7. Thoughts on 1998 amendments to Vermont Incorporation?  Would you be more/less likely to locate your business in Vermont?  
8. The text alludes to "Ben and Jerry's declining financial performance" on page 1.  Do you think the company's performance is poor/declining? 
9.  In the conclusion Harry Morgan says ROE is 7%, and that is "lousy by any measure".  Is it really lousy and does that mean the firm should be sold?
10.  pg 39, "declining financial performance triggered a number of takeover offers".  pg 45 /The Offers/ section says they pursued a joint venture due to competition, and when this didn't work Ben and Jerry's got takeover offers.  Do these sections agree?
   
* Method

You can approximate how much Ben and Jerry's is worth if it were a subsidiary of another firm by applying the other firms P/E multiple to Ben and Jerrys' earnings.  Note, Ben and Jerry's shareholders don't get this value---they get the acquisition price.  What it does give you is an idea of how undervalued Ben and Jerry's presently is.  This can be evidence of mismanagement---or evidence of nothing.

* Case Analysis

#+BEGIN_EXAMPLE
Pros/cons of each offer, which would you choose (this is the formal case analysis)?
#+END_EXAMPLE

* Case Question
